name: Quality Checks

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - "release/*"
    pull_request:
        branches:
            - main
            - "release/*"

jobs:
    # PHP 8.3 (MySQL) Job
    php-83-mysql:
        runs-on: ubuntu-22.04

        services:
            mysql:
                image: mysql:5.7
                ports:
                    - 3306:3306
                env:
                    MYSQL_ROOT_PASSWORD: secret
                    MYSQL_DATABASE: tenancy
                options: >-
                    --health-cmd="mysqladmin ping -h localhost -u root -psecret"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install PHP v8.3
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: mbstring, dom, fileinfo, mysql pdo_pgsql pdo_mysql gd
                  tools: composer:v2

            - name: Install PHP Dependencies
              run: composer install --no-progress --prefer-dist --optimize-autoloader

            - name: Run PHPUnit Tests
              run: ./vendor/bin/phpunit -c ci.mysql.phpunit.xml

    # PHP 8.3 (Mariadb) Job
    php-83-mariadb:
        runs-on: ubuntu-22.04

        services:
            mariadb:
                image: mariadb:10.5
                ports:
                    - 3306:3306
                env:
                    MYSQL_ROOT_PASSWORD: secret
                    MYSQL_DATABASE: tenancy
                options: >-
                    --health-cmd="mysqladmin ping -h localhost -u root -prootpassword"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install PHP v8.3
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: mbstring, dom, fileinfo, mysql pdo_pgsql pdo_mysql gd
                  tools: composer:v2

            - name: Install PHP Dependencies
              run: composer install --no-progress --prefer-dist --optimize-autoloader

            - name: Run PHPUnit Tests
              run: ./vendor/bin/phpunit -c ci.mysql.phpunit.xml

    # PHP 8.3 (Postgres) Job
    php-83-postgres:
        runs-on: ubuntu-22.04

        services:
            pgsql:
                image: postgres:13
                ports:
                    - 5432:5432
                env:
                    POSTGRES_PASSWORD: secret
                    POSTGRES_DB: tenancy
                options: >-
                    --health-cmd="pg_isready -U postgres -d tenancy"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install PHP v8.3
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: mbstring, dom, fileinfo, mysql pdo_pgsql pdo_mysql gd
                  tools: composer:v2

            - name: Install PHP Dependencies
              run: composer install --no-progress --prefer-dist --optimize-autoloader

            - name: Run PHPUnit Tests
              run: ./vendor/bin/phpunit -c ci.pgsql.phpunit.xml

            - name: Run PHPUnit Tests (Schema mode)
              run: ./vendor/bin/phpunit -c ci.pgsql.phpunit.xml ./tests/unit-tests/Database/ConnectionTest.php
              env:
                  TENANCY_DATABASE_DIVISION_MODE: schema
